### ISSUE TITLE
Google Play Store missing

### ISSUE THREAD

**Issue by lddd** [budtmo/docker-android#130]
Hello,

from the docs it says it includes Google Play Store, however i could not find one image yet where Play Store is included, which one is it?

Tested:
butomo1989/docker-android-x86-7.0
butomo1989/docker-android-x86-7.1.1
butomo1989/docker-android-x86-8.0
butomo1989/docker-android-x86-9.0

thanks in advance

**Comment by lsaadeh** [comment]
Would like this feature back! any update on the progress?

**Comment by billotronic** [comment]
https://github.com/budtmo/docker-android/blob/fcb89f27027059fae5d6b1c35f3c924ef66a762f/docker/Emulator_x86#L128

Not at a PC at the moment but it appears that its still being downloaded at the very least.

**Comment by lsaadeh** [comment]
Hey @budtmo thanks for all your work, just wondering if this bug is on your roadmap for the near future? happy to help test!

**Comment by marad9016100** [comment]
Hi all,

any update on this issue?
Maybe emulator should be incorporated by default SDK packages instead of being downloaded from the Internet?

I tried to install
"system-images;android-${API_LEVEL};google_apis_playstore;x86" "system-images;android-${API_LEVEL};google_apis_playstore;x86_64" "extras;google;google_play_services"

and add to .ini file
PlayStore.enabled=true

but with no luck.

**Comment by marad9016100** [comment]
Hi All,
I believe I've found the solution, still have to test it.
When I'll be sure about solution I can create the PR.

1) Do not use applinker, delete those lines
https://github.com/budtmo/docker-android/blob/fcb89f27027059fae5d6b1c35f3c924ef66a762f/docker/Emulator_x86#L124-L128

https://github.com/budtmo/docker-android/blob/fcb89f27027059fae5d6b1c35f3c924ef66a762f/docker/Emulator_x86#L124-L128

2)Download playstore and services with SDK, add:
"system-images;android-${API_LEVEL};google_apis_playstore;x86" "system-images;android-${API_LEVEL}; "extras;google;google_play_services"
Please note that some images are using x64 version.

https://github.com/budtmo/docker-android/blob/fcb89f27027059fae5d6b1c35f3c924ef66a762f/docker/Emulator_x86#L124-L128

3) avd config.ini is by default created with:
image.sysdir.1=system-images/android-{level}/google_apis/x86/

should be changed to
image.sysdir.1=system-images/android-{level}/google_apis_playstore/x86/

**Comment by lsaadeh** [comment]
@marad9016100 any luck?

**Comment by marad9016100** [comment]
I did not managed to automate the solution.
For now the workaround is to to build modified image locally.

For SDK 8.0 worakoround is:

1) Modify dockerfile - copy source of the Dockerfile + add one line

FROM butomo1989/docker-android-x86-8.0 (expand this source)
RUN yes | sdkmanager --licenses &&  sdkmanager "system-images;android-26;google_apis_playstore;x86" "extras;google;google_play_services" "system-images;android-26;default;x86" 

2) modify app.py to use google_apis_playstore instead of the google_apis

    creation_cmd = 'avdmanager create avd -f -n {name} -b google_apis_playstore/{sys_img} -k "system-images;android-{api_lvl};' \
                   'google_apis_playstore;{sys_img}" -d {device} -p {path}'.format(name=avd_name, img_type=IMG_TYPE,
                                                                        sys_img=SYS_IMG,
                                                                        api_lvl=API_LEVEL, device=device_name_bash,
                                                                        path=avd_path)

3) build  image from modifed Dockerfile

**Comment by marad9016100** [comment]
I managed to build modified image basing on
https://github.com/budtmo/docker-android/blob/master/docker/Emulator_x86

still it uses Android 5.0.1.
I have created image for Android 8.0, still it does not run stable - sometimes my test apps crash.

@budtmo 
Could you please publish all Dockerfiles or at least Dockerfile for 8.0 or 8.1 version?

**Comment by budtmo** [comment]
I have only 1 Dockerfile for emulator and you just need to change the value by using build-arg @marad9016100 . it would be great if someone can help to solve this issue.

**Comment by pgerlich** [comment]
@marad9016100 would you be willing to share what changes you had to make to the `Emulator_86` image in order to get this working?

**Comment by marad9016100** [comment]
Unfortunately my modifications do not result in creating the same image. There are other issues that do not reproduce on original image.
Basically to get playstore all that have to be changed is:
google_apis to google_apis**_playstore**

also adding this may be useful
google_play_services

**Comment by lsaadeh** [comment]
any progress on this one?

**Comment by JaysonAbilar** [comment]
Hi, we are currently encountering this issue also as our app also needs playstore in order to run properly. Would like to know there is progress on this issue? or do you have suggestions/workarounds for us to have an emulator with playstore? Thanks

**Comment by zek** [comment]
Having playstore disables "adb root" so appium doesn't work in this case.
