### ISSUE TITLE
Push notifications do not show up.

### ISSUE THREAD

**Issue by MateuszStachurzewski** [budtmo/docker-android#133]
Hi,
I have a problem with push notifications. They seem not to come up.
Unfortunately, I am not able to ascertain what the exact problem is.
I was trying to use different versions of the docker image as well as various devices but nothing works.

Does the device handle the notifications?

I will be grateful for help. 
Please, let me know if you need any more information to identify the problem.

**Comment by budtmo** [comment]
closed due to inactivity

**Comment by Louai99k** [comment]
Is there any update on this? I'm also facing the same problem and not receiving push notifications on the emulator
