### ISSUE TITLE
[Android 9.0] Screen bad displayed through noVNC

### ISSUE THREAD

**Issue by bonigarcia** [budtmo/docker-android#135]
**Operating System**
Ubuntu 18.04.1 LTS

**Docker Image**
butomo1989/docker-android-x86-9.0:1.6-p0

**Docker Version**  
Docker version 17.05.0-ce, build 89658be

**Docker Command to start docker-android**
> docker run --rm --privileged -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" butomo1989/docker-android-x86-9.0:1.6-p0

  
## Expected Behavior
I want to interact with the Android device through noVNC at http://localhost:6080/

## Actual Behavior
The screen of the Android device is not displayed properly:

![screenshot from 2019-01-08 16-28-31](https://user-images.githubusercontent.com/5413013/50840558-11a18980-1363-11e9-9f23-ef9affa3e54c.png)

**Comment by bonigarcia** [comment]
I've tried the same using the rest of images (version 8.1, 8.0, 7.0, and so on) and the problem only happens in version 9.0 (i.e. **butomo1989/docker-android-x86-9.0**).

**Comment by MalteToenjes** [comment]
I  have the same problem.....@budtmo could you  give some more information which emulator  version and which GPU mode you used?

**Comment by nonVoid** [comment]
Hi @bonigarcia @budtmo I got it working with xvfb using depth "24+32"
so switching the SCREEN_DEPTH variable to "24+32" should solve it

**Comment by budtmo** [comment]
Hi @nonVoid , 

awesome. could you create a PR for that?

**Comment by budtmo** [comment]
Hi @MalteToenjes ,

the version of emulator library you need to check inside the docker but I just release it so it should use the latest one and about the gpu is disabled. it can be found [here ](https://github.com/budtmo/docker-android/blob/master/src/app.py#L206-L209). if you can improve things there, it would be great if you can create a PR. :D
