### ISSUE TITLE
Support other emulator devices

### ISSUE THREAD

**Issue by budtmo** [budtmo/docker-android#14]
- [x] Samsung Galaxy S7 
- [x] Samsung Galaxy S7 Edge
- [x] Samsung Galaxy S8
- [x] Samsung Galaxy S9
- [x] Samsung Galaxy S10

**Comment by v3g3t4x** [comment]
When this new devices ?

**Comment by butomo1989** [comment]
Hi @v3g3t4x ,

I am working on something else at the moment, but it would be great if you can help us in this improvement. It will also benefit others.

**Comment by v3g3t4x** [comment]
If you provide a tutorial or guideline we can create it..

**Comment by mgrazioli** [comment]
Also I need to this Documentation please

**Comment by wsegurar** [comment]
Hello,

How I can help, I need support for Samsung Galaxy S7 Edge

**Comment by v3g3t4x** [comment]
@butomo1989  please help us 👍

**Comment by diemol** [comment]
You could check how the Galaxy S6 is being built and find out what values are needed for the S7.

**Comment by butomo1989** [comment]
Hi @v3g3t4x @mgrazioli @wsegurar , 

Here is the steps:
1. you need to have device skin and put [here](https://github.com/butomo1989/docker-android/tree/master/devices/skins) 
2. do the same with [device profile](https://github.com/butomo1989/docker-android/tree/master/devices/profiles)
3. build the image and check locally. If it works, could you create PR for that? :)

Note: please use the same name format like others.

**Comment by mgrazioli** [comment]
Hi budi,is it possible change resolution's android emulator? Why when do I start the emulator for example Samsung s7, I see all icons small?

**Comment by avecc** [comment]
Any update on that ? :(

**Comment by dwwhalen** [comment]
@butomo1989 I would like to add Samsung Galaxy S8 emulator.  I've cloned the repo and added the device profile and device skin.  Now I want to test locally.  How do I build a local image that incorporates my updates?  For example, I'd like to build the docker-android-x86-9.0 image locally.  Thanks.
