### ISSUE TITLE
Screenshot with Appium fails with budtmo/docker-android-x86-5.1.1

### ISSUE THREAD

**Issue by izaneuski** [budtmo/docker-android#146]
Operating System: 
Ubuntu 16.04.1 LTS

Docker Image:
budtmo/docker-android-x86-5.1.1

Docker Version:  
18.09.1, build 4c52b90

Docker Command to start docker-android:  
docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 -e APPIUM=true -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-5.1.1
  
## Expected Behavior
I'm trying to run a test with java and Appium using the URL: http://localhost:4723/wd/hub
Test fails after trying [take screenshot](http://appium.io/docs/en/commands/session/screenshot/):
```
I/appium  ( 4580): channel read: GET /wd/hub/session/80d6f484-5998-40b6-a939-444eef6baa9e/screenshot
I/appium  ( 4580): Capture screenshot command
D/gralloc_ranchu( 4569): Emulator without host-side GPU emulation detected. Loading gralloc.default.so from /vendor/lib/hw/gralloc.default.so...
D/gralloc_ranchu( 4569): gralloc.default.so not found in /vendor. Trying /system/lib/hw/gralloc.default.so...
D/gralloc ( 1141): Registering a buffer in the process that created it. This may cause memory ordering problems.
E/libEGL  ( 1141): called unimplemented OpenGL ES API
E/SurfaceFlinger( 1141): glCheckFramebufferStatusOES error 785662635
E/SurfaceFlinger( 1141): got GL_FRAMEBUFFER_COMPLETE_OES error while taking screenshot
E/appium  ( 4580): Exception while handling action in: io.appium.uiautomator2.handler.CaptureScreenshot
E/appium  ( 4580): io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set?
E/appium  ( 4580): 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(ScreenshotHelper.java:70)
E/appium  ( 4580): 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:48)
```

## Actual Behavior
Same tests works fine with image budtmo/docker-android-x86-6.0 and higher - screenshots are taking

**Comment by budtmo** [comment]
Hi @izaneuski , 

I think you need to create an issue on [Appium repository](https://github.com/appium/appium), because it is not related to this project, so I will close this ticket but feel free to reopen it.
