### ISSUE TITLE
Guidance for initial implementation

### ISSUE THREAD

**Issue by deviran01** [budtmo/docker-android#147]
Hi

Operating System: 
`Ubuntu 16.04
`

Docker Image:
` budtmo/docker-android-x86-8.1`

or
` budtmo/docker-android-x86-9.0
`
Docker Version:  
`18.06.1-ce, build e68fc7a
`
Docker Command to start docker-android:  
` docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1`
or
`docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-9.0`

## Expected Behavior
open browser and go to http://127.0.0.1:6080
Just black screen and can open terminal or switch between tabs (can't see emulator)

## Actual Behavior
How I can run android emulator UI

please help me.

**Comment by HasBert** [comment]
I have the same problem if I scroll while the emulator is active in the browser. As long a I'm no scrolling everthing is ok. To solve the problem I go in full windowed mode with my browser and hope not touch the mouse wheel xD. I looked up the logs with:
`docker exec -it android-container tail -f /var/log/supervisor/docker-android.stdout.log`
but nothing happens there. Until now I haven't found something, which can solve the problem, unless restarting with `docker restart container-id` and not scrolling again. xD

**Comment by stephane-r** [comment]
Same problem : black screen on localhost:6080.
I've try to run emulator manualy, but i've an error about the 32 bit environment :/

**Comment by budtmo** [comment]
closed, duplicated #120

**Comment by deviran01** [comment]
I solve this problem
I change OS from Windows 10 to Xubuntu 64bit
install docker and run the android_X86 image in the docker 
and finally can see emulator with noVNC in the browser https://localhost:6080
