### ISSUE TITLE
The emulator reset when the Android app is being installed. 

### ISSUE THREAD

**Issue by estefafdez** [budtmo/docker-android#149]
**Operating System:**  CentOS 7

**Docker Image:** butomo1989/docker-android-x86-8.1

**Docker Version:**  18.06.1-ce

**Docker-compose version (Only if you use it):**  None

**Docker Command to start docker-android:**  
`docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1`

and 

`docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Nexus 5" --name android-container budtmo/docker-android-x86-8.1`
  
## Actual Problem

Hello, 

I am using your docker image (budtmo/docker-android-x86-8.1) to execute Appium test on a Maven project. 

As you are using not using maven (you had gradle installed), I had to install Maven and set the M2_HOME variable on the image. 

Appart from that I had to change the last line of the  **~/.profile** file for: 
`tty -s && mesg n `
in order to make it work. 

With both devices I had the same problem. The emulator is running (I can see it on the 6080 port) and Appium is installed, but after that, when Appium is installing the android application, the emulator is reset and start booting. 

If I run the same command on the command line with the emulator running the install android app works and I can open the app but not running the Appium Maven project.
This project is a simple Maven project using Appium which works properly and its already tested for us (on Linux, Mac and Windows) so the problem is not the project itself, 
I think its something related to the emulator properties (internal memory probably). 

Is there any solution you might think? You can see a GIF with the problem ihere:
https://imgur.com/6UqxbMU

Also the full log is attached into this issue. 
[emulator_failed_log.txt](https://github.com/budtmo/docker-android/files/2986994/emulator_failed_log.txt)

Thank you very much for your hard work.

**Comment by budtmo** [comment]
duplicated #125
