### ISSUE TITLE
My mulator has been stuck in the boot interface

### ISSUE THREAD

**Issue by lijingchun0** [budtmo/docker-android#150]
**Please make sure that it is an issue / a feature request. If it is a question / help wanted, please visit [our group chat](https://gitter.im/budtmo/docker-android). Thank you!**

Operating System: 

centos7 in vm
Docker Image:

budtmo/docker-android-x86-8.1
Docker Version:  

17.09.1-ce
Docker-compose version (Only if you use it):  

Docker Command to start docker-android:  

  docker run --privileged -d -p 6080:6080 4723:4723 -e DEVICE="Samsung Galaxy S6" -e APPIUM=true --name android-container  budtmo/docker-android-x86-8.1

**Comment by budtmo** [comment]
duplicated #120
