### ISSUE TITLE
Not have internet access in emulator.

### ISSUE THREAD

**Issue by Abhi310** [budtmo/docker-android#153]
**The emulator don't have internet access. Can't open any web page on chrome app.  In particular the app i have to test needs internet access. How to give internet access to the emulator?**
I am on a corporate network, so have proxy server. Internet on browser(host system) is working fine. Docker also have internet access(can pull and push images). Tried setting proxy on emulator settings option, didn't work.

Operating System: Ubuntu 16.04

Docker Image: butomo1989/docker-android-x86-9.0

Docker Version:  17.06.0-ce

Docker-compose version (Only if you use it):  

Docker Command to start docker-android:  docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Nexus 4" --name android-container budtmo/docker-android-x86-9.0

**Comment by amitg25** [comment]
@Abhi310 , are you running it on Mac? If so, how did you manage to even start emulator? I am strugeling from last week and No one has yet responded on how can we setup VM to run with this docker image.

**Comment by Abhi310** [comment]
@amitg25 , no man i am not running it on Mac. My OS is Ubuntu 16.04, no VM. Could have helped you but have no idea how to run it on Mac.

**Comment by budtmo** [comment]
duplicated #78
