### ISSUE TITLE
0 Android devices connected

### ISSUE THREAD

**Issue by mcopjan** [budtmo/docker-android#154]
Using the following compose file:
version: "2.2"

services:
  selenium_hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444

  samsung_galaxy_web_7.1.1:
    image: budtmo/docker-android-x86-7.1.1
    privileged: true
    # Increase scale number if needed
    scale: 1
    depends_on: 
      - selenium_hub
    ports:
      - "6080:6080"
    volumes:
      - ./video-samsung_7.1.1:/tmp/video
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - MOBILE_WEB_TEST=true
      - AUTO_RECORD=false

![image](https://user-images.githubusercontent.com/20699180/56322799-e6001d80-6161-11e9-8234-32457ff44304.png)

adb devices returns 0 connected devices. What am I missing?

**Comment by budtmo** [comment]
duplicated #120
