### ISSUE TITLE
docker-android-x86-8.1 & 8.0 failed to install google play

### ISSUE THREAD

**Issue by eyal919** [budtmo/docker-android#157]
**Please make sure that it is an issue / a feature request. If it is a question / help wanted, please visit [our group chat](https://gitter.im/budtmo/docker-android). Thank you!**

**Latest Docker Image of**
budtmo/docker-android-x86-8.1 & budtmo/docker-android-x86-8.0

```
#cat /var/log/supervisor/adb-utils.stderr.log
adb: failed to install /root/google_play_services.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
adb: failed to install /root/google_play_store.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.android.vending signatures do not match the previously installed version; ignoring!]

```

**Comment by budtmo** [comment]
duplicated #130
