### ISSUE TITLE
emulator running very slow

### ISSUE THREAD

**Issue by ciekawy** [budtmo/docker-android#159]
**Please make sure that it is an issue / a feature request. If it is a question / help wanted, please visit [our group chat](https://gitter.im/budtmo/docker-android). Thank you!**

Operating System: 
Ubuntu running on DIgitalOcean

Docker Image:
butomo/docker-android-x86-8.1

Docker Version:  
18.09.6

Docker Command to start docker-android:  
```
docker run --rm --privileged --device /dev/kvm  -d   -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 -e APPIUM=true butomo/docker-android-x86-8.1
```
  
## Expected Behavior
emulator boots in reasonable time ( around 5mins could be acceptable)

## Actual Behavior
it takes some 20 mins or more for emulator to boot. 

I know this has been reported before and with suggestions that cloud other than bare metal or some dedicated ones will not work. However IMO this should work on DigitalOcean as I see full virtualization support 

```
# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           4
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:            4
CPU MHz:             2294.608
BogoMIPS:            4589.21
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves pku ospke md_clear
```

I feel like some flags or config could help running emulator in reasonable speed

**Comment by tadashi0713** [comment]
@ciekawy How about adding `EMULATOR_ARGS="-gpu swiftshader_indirect"`

**Comment by ciekawy** [comment]
Thats interesting, I'll give it a try, wondering whats the GPU impact on
overall performance...

niedz., 19 maj 2019 o 23:52 Tadashi Nemoto <notifications@github.com>
napisał(a):

**Comment by ciekawy** [comment]
thats amazing! now emulator is starting in less than 3 minutes! probably this may be worth to add to the docs. To be able to execute what I did actually was to add 
```
EMULATOR_ARGS="-gpu swiftshader_indirect -accel on"
LD_LIBRARY_PATH=/root/emulator/lib64/qt/lib/:/root/emulator/lib64/:/root/emulator/lib64/gles_swiftshader/
```

not sure if the `accel on` is reaquired, yet the `LD_LIBRARY_PATH` adds paths to the libs not visible by default.

**Comment by tadashi0713** [comment]
👍

**Comment by budtmo** [comment]
Added in release [1.8-p1](https://github.com/budtmo/docker-android/releases/tag/1.8-p1)

**Comment by ordenador** [comment]
in azure with VM size 'Standard_D4s_v3' does not works (i am using docker image: budtmo/docker-android-x86-8.0:1.8-p1)

**Comment by ciekawy** [comment]
and was it working before? could you try adding 
```
LD_LIBRARY_PATH=/root/emulator/lib64/qt/lib/:/root/emulator/lib64/:/root/emulator/lib64/gles_swiftshader/
```
? can be wrong by my feeling is that this is missing in the recent PR

also I'd be curious about azure performance (in the past I found it pretty slow when comparing to equivalent digitalocean)

**Comment by ordenador** [comment]
yes with option '-gpu off' work,  a little slow , but work

the new default option '-gpu swiftshader_indirect -accel on' with your LD_LIBRARY_PATH environment does not work either

and, yes Azure is very slow, and i needed to add a lot appium configuration in my code, for example: uiautomator2ServerInstallTimeout, androidInstallTimeout, androidDeviceReadyTimeout, adbExecTimeout ...

my next steep are: testing directly with kubernetes in Azure and later testing with GCP

> and was it working before? could you try adding
> 
> ```
> LD_LIBRARY_PATH=/root/emulator/lib64/qt/lib/:/root/emulator/lib64/:/root/emulator/lib64/gles_swiftshader/
> ```
> 
> ? can be wrong by my feeling is that this is missing in the recent PR
> 
> also I'd be curious about azure performance (in the past I found it pretty slow when comparing to equivalent digitalocean)

**Comment by ciekawy** [comment]
I'd propose you to `docker exec -ti <container-name> bash and try executing emulator inside to see the logs - thats how I did figure out missing libraries. Considering `-gpu off` works well I'd assume the nested virtualization is configured properly so maybe there is still some library missing (or version/path differs in compare to my setup)

**Comment by budtmo** [comment]
in my opinion, using gpu off is not an option because it doesn't make sense to use docker-android if it is really slow. this is also the reason why we do not support Mac OS any more.I think it would be better if you find machine which support hardware acceleration @ordenador @ciekawy 

@ordenador it would be great if you can share your configuration on deploying Docker-Android on AWS or GCP using any tool, so anyone can benefit from it. you can add into [exiting documentation](https://github.com/budtmo/docker-android/blob/master/README_CLOUD.md) about that and create a PR.

**Comment by ordenador** [comment]
> in my opinion, using gpu off is not an option because it doesn't make sense to use docker-android if it is really slow. this is also the reason why we do not support Mac OS any more.I think it would be better if you find machine which support hardware acceleration @ordenador @ciekawy
> 
> @ordenador it would be great if you can share your configuration on deploying Docker-Android on AWS or GCP using any tool, so anyone can benefit from it. you can add into [exiting documentation](https://github.com/budtmo/docker-android/blob/master/README_CLOUD.md) about that and create a PR.

sure, if i do something with GCP i going to share it
