### ISSUE TITLE
deepin can't open web server

### ISSUE THREAD

**Issue by Louis-me** [budtmo/docker-android#165]
## Operating System: 
- 4.15.0-30deepin-generic #31 SMP Fri Nov 30 04:29:02 UTC 2018 x86_64 GNU/Linux

## Docker Image:
- budtmo/docker-android-x86-8.1 

## Docker Version:  
- Docker version 18.09.6, build 481bc77

## steps
- Docker Command to start docker-android:  
```
 docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1
```
- docker ps
```
XXXPC:$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                        PORTS                                                                NAMES
c17fdd6b648a        budtmo/docker-android-x86-8.1   "/bin/sh -c '/usr/bi…"   38 hours ago        Up About a minute (healthy)   0.0.0.0:5554-5555->5554-5555/tcp, 4723/tcp, 0.0.0.0:6080->6080/tcp   android-container

```  
- docker-machine ip default
```
XXX-PC:/$ docker-machine ip default
192.168.99.100
```
- open http://192.168.99.100:6080 
## Expected Behavior
- Open  http://192.168.99.100:6080  

## Actual Behavior
- Can't open http://192.168.99.100:6080  
```
Unable to access this site 192.168.99.100 rejected our connection request.
Please try the following:

Check network connection
Check the proxy server and firewall
ERR_CONNECTION_REFUSED
```

**Comment by budtmo** [comment]
Hi @Louis-me , 

could you try it again with the latest version? because it works fine on my side

**Comment by Louis-me** [comment]
I try again，works for me，thanks
