### ISSUE TITLE
budtmo/docker-android-x86-8.1   image failed to start

### ISSUE THREAD

**Issue by 949346817** [budtmo/docker-android#169]
Operating System: 

Linux autotest-68 4.15.0-50-generic #54~16.04.1-Ubuntu SMP Wed May 8 15:50:20 UTC 2019 i686 i686 i686 GNU/Linux

Docker Image:
budtmo/docker-android-x86-8.1

Docker Version:  
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:17:26 2019
 OS/Arch:           linux/386
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:53:57 2019
  OS/Arch:          linux/386
  Experimental:     false

I use "docker logs --since="2019-07-03" --tail=10 android-container" to view the log.The following is the log。

**standard_init_linux.go:211: exec user process caused "exec format error"**

**Comment by trinhpham** [comment]
Your host might need to be set up with x64 OS version.

**Comment by Nottt** [comment]
I have same issue. 

I'm on Ubuntu 18.04.3 LTS x64
