### ISSUE TITLE
Update REAL_DEVICE to use `scrcpy` instead of `asm`

### ISSUE THREAD

**Issue by trinhpham** [budtmo/docker-android#174]
## 🚀 Feature Request

Idea: 

`asm` maintenance is stopped by its owner 6 years ago. Keep using it might let us be into security or performance issues. I see that GennyMobile has opened source of [scrcpy](https://github.com/Genymobile/scrcpy) which has many features. Should we switch into `scrcpy`?

**Comment by budtmo** [comment]
it is duplicated #131
