### ISSUE TITLE
ChromeDriver not working

### ISSUE THREAD

**Issue by dextermapalya** [budtmo/docker-android#182]
## 💬 Questions and Help
Hi,
I could not get this code to work in python 
https://github.com/budtmo/docker-android/blob/master/example/android/python/msite_simple_chrome.py

I get below error message

selenium.common.exceptions.WebDriverException: Message: Error forwarding the new session cannot find : Capabilities {appActivity: com.google.android.apps.chr..., appPackage: com.android.chrome, browserName: chrome, deviceName: Android Emulator, platformName: android}

I  connected into the docker container and verified that com.android.chrom package exists.
I can also launch the chrome browser using noVNC.

**Comment by budtmo** [comment]
the test is not up to date and it is never be used, I am planning to remove it. You need to try with other UI test. I will close this ticket.
