### ISSUE TITLE
Emulator does not come up

### ISSUE THREAD

**Issue by lkkushan101** [budtmo/docker-android#184]
## 🐛 Bug Report

I pulled the docker container
docker pull budtmo/docker-android-x86-8.1
Ran the container 
 docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Nexus One" --name android-container budtmo/docker-android-x86-8.1

Accessed in the browser 
http://127.0.0.1:6080/

But i see the logo but not the emulator... 

What should i do ?

**Comment by kevenfeng** [comment]
me too 
 ubuntu 16 Docker version 19.03.1

**Comment by lkkushan101** [comment]
do i have to change the docker version? please advice me to solve this issue

**Comment by alexcanDvlpr** [comment]
I have the same problem. Windows 10 Docker version 18.09.2.

**Comment by dwwhalen** [comment]
This seems to be a very popular problem.  There is a closed issue that addresses it pretty well https://github.com/budtmo/docker-android/issues/120

My understanding is you need to be using Ubuntu.  I have a Windows 10 laptop and we able to get it working with Ubuntu on VMware Workstation 15 Player.  For the VM settings Virtualization engine I chose "Virtualize Intel VT-x/EPT or AMD-v/RVI".  I had no luck with Oracle Virtual Box.

**Comment by yagelardan** [comment]
Try to add "-p 4723:4723", then do "adb connect localhost:5555"

**Comment by shangyou** [comment]
After the installation is completed, access through the browser, the following picture appears, the phone page does not appear, is it correct?
![1564918789047](https://user-images.githubusercontent.com/2002594/62423118-ba447b80-b6ef-11e9-9f93-78ac4d065cda.jpg)

**Comment by panyang1217** [comment]
+1 
Azure VM with Ubuntu 18.04

**Comment by Grohden** [comment]
#93 doesn't have a nice title, but I think that is the same problem.

I've made [this comment](https://github.com/budtmo/docker-android/issues/93#issuecomment-516092215) and it might help you to understand the problem.. 

it seems that there are two `emulator` executables on the `path`, but the wrong one is picked, you can confirm this by calling `which emulator` (inside the container of course) and checking that it returns `/root/tools/emulator` instead of `/root/emulator/emulator`

In case this happens, you can start the emulator inside the container with `/root/emulator/emulator -avd YOUR_EMULATOR_NAME`.

If you wish to start the container with the emulator opened I don't have any ideas :/ using a script on the run command doesn't seems to work cuz the emulator is created using the DEVICE_NAME _after_ the container is up/started

I've tried to create a image with this (to make the `path` use the correct emulator):
```
FROM budtmo/docker-android-x86-8.1

# Set ENV
ENV NODE_VERSION=v12.7.0 \
    PATH=$ANDROID_HOME/emulator
```

but still the emulator doesn't start when I start the container

**Comment by eyal919** [comment]
same for me... using latest docker image budtmo/docker-android-x86-6.0 not bring up the emulator while version 1.7-p1 is working fine.

adb shell return: error: no devices/emulators found

this is the log output of docker-android.stderr.log
```
Error: AVD not created.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/src/app.py", line 238, in <module>
    run()
  File "/root/src/app.py", line 217, in run
    prepare_avd(device, avd_name, dp_size)
  File "/root/src/app.py", line 112, in prepare_avd
    subprocess.check_call(creation_cmd, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'avdmanager create avd -f -n nexus_5_6.0 -b google_apis/x86 -k "system-images;android-23;google_apis;x86" -d Nexus\ 5 -p /root/android_emulator' returned non-zero exit status 1.
```

**Comment by aranvic** [comment]
the same problem on MacOs, Mojave 10.14

**Comment by shangyou** [comment]
Emulator was not previously initialized. Preparing a new one...

![image](https://user-images.githubusercontent.com/2002594/62719047-a70c1580-ba39-11e9-8921-64807528982c.png)

**Comment by lozadavictor** [comment]
same problem here ! ubuntu 18.04 
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by lozadavictor** [comment]
i solve this issue allowing virtualization in my bios config

**Comment by eyal919** [comment]
Any updates?

**Comment by budtmo** [comment]
duplicated #93

**Comment by alexcanDvlpr** [comment]
I solve this issue.

I have used a virtual machine with Ubuntu 18.04 in VMWare, in which I have installed Docker and I have followed the steps of this project and working.

The problem I found is that VirtualBox does not support nested-virtualization and VMWare does.

I hope it helps you.

**Comment by gitamineHM** [comment]
@budtmo  The issue is the same with windows 7 and docker with linux container.
