### ISSUE TITLE
I need a arm docker image

### ISSUE THREAD

**Issue by id0612** [budtmo/docker-android#185]
## 🚀 Feature Request

Idea: 
Build their own cloud phones and run an application, such as a game, 24 hours a day. Usually they only support ARM.

Problems that want to be solved:
Running third-party applications 24 hours a day, they only support ARM.

Note:  
Provide an effective method or simply provide an image of android 5.0 or higher that can run like the current images. I think it's good.

**Comment by budtmo** [comment]
Hi @id0612 , 

I dont support arm image since last year, because it is really slow (it takes 10 minutes to make the emulator ready), so in my opinion it doesnt make sense to use it if it is too slow and flaky. 

maybe you can request for apk that is for x86 image. 

I will close the ticket for now.

**Comment by id0612** [comment]
Since all the apps I need to run only support ARM, X86 is meaningless to me, but thank you all the same.
