### ISSUE TITLE
Build docker image locally

### ISSUE THREAD

**Issue by GerardLarwa** [budtmo/docker-android#196]
I want to build docker-android image locally. I clone the whole project and try build image by below command:

> docker build -t "android-test:local" -f docker/Emulator_x86 .

The image is built, but there is no emulator. Inside container I can't find any available devices. It seems that app.py wasn't execute. There is also no logs in  /var/log/supervisor/docker-android.stdout.log. Which way should I build my local image?

**Comment by Arne-B** [comment]
using the release*.sh scripts works for me.
./release_real.sh build version
for example.

**Comment by GerardLarwa** [comment]
Using script didn't help.

**Comment by luisiluck** [comment]
same to me I just run `docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1` as it is mentioned in the .md... After image fetching the container runs but no emulator inside

**Comment by budtmo** [comment]
duplicated #93
