### ISSUE TITLE
Unable to see Emulator

### ISSUE THREAD

**Issue by demersonh** [budtmo/docker-android#198]
Hi,

I am trying to run this one on an azure VM but can't get the android emulator to pop-up. I am able to connect to noVNC but I can't see any emulator popping up.

When running adb -H localhost devices nothing shows up, it is like it is offline.

Has anyone experienced this? Could anyone please assist?

Regards,
Demerson

**Comment by mattcopas** [comment]
+1 I'm also experiencing this - running on both MacOS and Ubuntu 18.04

**Comment by mattcopas** [comment]
@demersonh Try running (from inside the docker container):

`emulator -list-avds` to list your virtual devices,

then run `emulator @devide_name`

I get an error:

```
statvfs('/root/android_emulator/snapshots/default_boot/ram.img') failed: No such file or directory
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.
```

Running on MacOSX

**Comment by demersonh** [comment]
@mattcopas I ended up removing that one as it didn't work. I was trying to run it within an azure VM.

I still couldn't find an alternative :(

I saw a few more people were having the same issues but none of the solutions appear to work... Anyways, I hope you can manage to work it out and use this one. If I mind any alternative, I will share it with you.

Cheers

**Comment by cemo** [comment]
I think that this is because we are using "Docker for Mac" which is using "hypervisor". Hypervisor is not supporting nested virtualization. Instead we need to setup a docker machine with VirtualBox and use it for this purpose. 

I think using a ARM based device will solve our problem.

**Comment by TheoNeUpKid88** [comment]
@cemo please update the ticket if your approach does resolve this issue. - Thanks

**Comment by cemo** [comment]
we added `firebase.json` at the root of project. I have no idea why it is working on osx where as it is not in a container but seems the culprit was it.

**Comment by cemo** [comment]
I gave up these approaches since latest Android API's are not supporting ARM based emulators. So I decided to use Genymotion on my box with Docker based development environment. I have not completed my work but it think it will be working.

**Comment by mattcopas** [comment]
I've managed to get this working on Ubuntu 18.04 with a slightly customised dockerfile:

```
FROM budtmo/docker-android-x86-9.0
RUN sdkmanager --update
```

`docker build -t my-custom-emulator .`

`docker run --privileged -it -p 6080 -e DEVICE="Nexus 5" my-custom-emulator`

Privileged mode is essential, and the sdkmanager update helped too.

**Comment by cemo** [comment]
Linux boxes are supporting nested virtualization. It would not be surprise it to be working.

**Comment by TheoNeUpKid88** [comment]
This could potentially be another issue. Though, when I attempt to run e.g., `docker run --privileged -it -p 6080 -e DEVICE="Nexus 5" my-custom-emulator` with a volume to _pre-load_ an APK the results the same, with the emulator crashing and/ or not being visible.

**Comment by gitkav** [comment]
Hi,

I am facing the same issue. My docker is running on Mac. Is there any solution for this issue?

**Comment by budtmo** [comment]
duplicated #93
