### ISSUE TITLE
Documentation is not up to date for building a gradle project

### ISSUE THREAD

**Issue by sealabr** [budtmo/docker-android#200]
## 🐛 Bug Report

Operating System: 
5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Docker Image:
docker-android-x86-8.1

Docker Version:  
Docker version 19.03.2, build 6a30dfc

Docker-compose version:
1.24.1, build 4667896b

Docker Command to start docker-android:  
docker run -it --rm -v $PWD/android-testing/ui/espresso/BasicSample:/root/tmp budtmo/docker-android-x86-8.1 tmp/gradlew build
  
## Expected Behavior
Start docker

## Actual Behavior
Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"tmp/gradlew\": stat tmp/gradlew: no such file or directory": unknown

Edit...
maybe is this empty folder?
```

fabio@fabio-pc:~/Docker/android-testing/ui/espresso/BasicSample$ ls
fabio@fabio-pc:~/Docker/android-testing/ui/espresso/BasicSample$ ll
total 8
drwxr-xr-x 2 root root 4096 out  8 13:13 ./
drwxr-xr-x 3 root root 4096 out  8 13:13 ../
fabio@fabio-pc:~/Docker/android-testing/ui/espresso/BasicSample$ ls -lah
total 8,0K
drwxr-xr-x 2 root root 4,0K out  8 13:13 .
drwxr-xr-x 3 root root 4,0K out  8 13:13 ..
fabio@fabio-pc:~/Docker/android-testing/ui/espresso/BasicSample$
```

**Comment by sealabr** [comment]
why this occur?

```
fabio@fabio-pc:~/Docker$ git clone git@github.com:googlesamples/android-testing.git
Cloning into 'android-testing'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by sealabr** [comment]
Looks like they changed the repo:

https://github.com/android/testing-samples

this worked:

`docker run -it --rm -v $PWD/testing-samples/ui/espresso/BasicSample:/root/tmp budtmo/docker-android-x86-8.1 tmp/gradlew build`

**Comment by budtmo** [comment]
Hi @sealabr , 

it seems the documentation is not up to date. Do you want to create a PR for it? It would be great.
