### ISSUE TITLE
Android emulator doesnt show on VNC

### ISSUE THREAD

**Issue by sealabr** [budtmo/docker-android#201]
## 🐛 Bug Report

Hello, I cant open the android emulator, I'm doing something wrong?

first create a docker container and then build the project, right?

Operating System:
5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Docker Image:
docker-android-x86-8.1

Docker Version:
Docker version 19.03.2, build 6a30dfc

Docker-compose version:
1.24.1, build 4667896b

Docker Command to start docker-android:
$ docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 --name android-container-appium budtmo/docker-android-real-device

$ docker run -it --rm -v $PWD/android-testing/ui/espresso/BasicSample:/root/tmp budtmo/docker-android-x86-8.1 tmp/gradlew build

## Actual Behavior

![Screenshot from 2019-10-08 14-08-56](https://user-images.githubusercontent.com/21187479/66417168-cee60e00-e9d5-11e9-97cb-1a789aec2162.png)

```
fabio@fabio-pc:~/Docker$ sudo docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
3b625936b5a0        budtmo/docker-android-real-device   "/bin/sh -c '/usr/bi…"   20 minutes ago      Up 20 minutes       0.0.0.0:4723->4723/tcp, 0.0.0.0:5554-5555->5554-5555/tcp, 4567/tcp, 0.0.0.0:6080->6080/tcp   android-container-appium



fabio@fabio-pc:~/Docker$ sudo docker run -it --rm -v $PWD/testing-samples/ui/espresso/BasicSample:/root/tmp budtmo/docker-android-x86-8.1 tmp/gradlew build
Downloading https://services.gradle.org/distributions/gradle-4.6-all.zip
.............................................................................................................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-4.6-all/5vpsfhg9sgbuqofrbh1l21ueq4/gradle-4.6-all.zip to /root/.gradle/wrapper/dists/gradle-4.6-all/5vpsfhg9sgbuqofrbh1l21ueq4
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-4.6-all/5vpsfhg9sgbuqofrbh1l21ueq4/gradle-4.6/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :buildEnvironment 

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
No dependencies

A web-based, searchable dependency report is available by adding the --scan option.


BUILD SUCCESSFUL in 1m 28s
1 actionable task: 1 executed
```

And stoped here...

**Comment by sealabr** [comment]
# docker-android.stderr.log^C
# tail docker-android.stderr.log
xterm: cannot load font "-Misc-Fixed-bold-R-*-*-13-120-75-75-C-60-ISO8859-1"

**Comment by budtmo** [comment]
duplicated #93
