### ISSUE TITLE
How can i run an android emulator

### ISSUE THREAD

**Issue by kucharskikrzysiek** [budtmo/docker-android#203]
## 💬 How i can run android emulator in the container?
I ran line 

`docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 -e DEVICE="Samsung Galaxy S9" -e MOBILE_WEB_TEST=true -e APPIUM=true --name android-container budtmo/docker-android-x86-8.1`

On the 'desktop' i can see only appium server console. 
I ran terminal emulator and after command
`emualtor -list-avds `
i got a 1 device image but how i can open emulator and see image of phone as in the movie 

> https://youtu.be/pQdpjuYwvp8?t=707

Thanks in advance for help

**Comment by slasom** [comment]
I have the same problem...

**Comment by trinhpham** [comment]
Most of people ask the same question when try to run the image on Windows or Mac host.
You should make sure that you read the prerequisites carefully, and check if your Docker host has support for virtualization (vmx).

**Comment by slasom** [comment]
I have a VirtualBox Machine with Ubuntu OS 18 and virtualization activated but **don't work**. My OS personal where have VirtualBox installed is Windows 10 Home and have virtualization with Intel.

**Comment by slasom** [comment]
I don't know if I execute badly but I already had activated the virtualization in Windows and in Virtual Vox but don't work... I execute the command that are put in your issue

**Comment by trinhpham** [comment]
@slasom You have to make sure your Virtualbox has enabled "Nested virtualization" feature, something like
![image](https://user-images.githubusercontent.com/9128061/66988196-53c6db00-f0ec-11e9-9ad3-6273bb4d5f59.png)

Maybe, you'll need to install the [VirtualBox Extension Pack](https://download.virtualbox.org/virtualbox/6.0.14/Oracle_VM_VirtualBox_Extension_Pack-6.0.14.vbox-extpack)
