### ISSUE TITLE
Emulator crashes when selecting more in tool bar

### ISSUE THREAD

**Issue by ssmuthukumaran** [budtmo/docker-android#207]
## 🐛 Bug Report

Operating System: Ubuntu 19.10
Docker Image: budtmo/docker-android-x86-8.1
Docker Version:  19.03.3-ce
Docker Command to start docker-android:  
docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1
  
## Expected Behavior
Clicking on more button on the menu bar next to emulator should open the settings menu for user to select settings needed.

## Actual Behavior
Clicking on more button on the menu bar next to emulator crashes the emulator

My android application involves opengl rendering and i would set opengles renderer option to openGL ES 3.0 through settings, when i clicked on settings in the latest emulator it crashed.

``

**Comment by augustynski-lukasz** [comment]
I have similar behaviour but when click on any toolbar button.

**Comment by BigBen2003** [comment]
== English ==
OS: Ubuntu 18.04

Info: This text was translated by Google.

If you click any button in the menu bar next to the emulator, the emulator crashes

After restarting the Docker container, the emulator is no longer displayed.

== German ==
OS: Ubuntu 18.04

Wenn in der Menüleiste neben dem Emulator auf eine beliebige Schaltfläche geklickt wird, stürzt der Emulator ab

Nach dem Neustart  vom Docker-Container wird der Emulator nicht mehr angezeigt.

**Comment by budtmo** [comment]
duplicated #223
