### ISSUE TITLE
Launching emulator, complains 32 bits

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [budtmo/docker-android#208]
## 🐛 Bug Report

Operating System: 
CentOS 7.2

Docker Image:
budtmo/docker-android-x86-8.1

Docker Version:  
Docker version 19.03.2, build 6a30dfc

Docker-compose version (Only if you use it):  
Not used

Docker Command to start docker-android:  
docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" -e LANGUAGE=es -e COUNTRY=ES --name android budtmo/docker-android-x86-8.1

  
## Expected Behavior
Being able to launch android emulator

## Actual Behavior

When launching:
   emulator

I receive this error: 

WARNING: Cannot decide host bitness because $SHELL is not properly defined; 32 bits assumed.
ERROR: 32-bit Linux Android emulator binaries are DEPRECATED, to use them
       you will have to do at least one of the following:

       - Use the '-force-32bit' option when invoking 'emulator'.
       - Set ANDROID_EMULATOR_FORCE_32BIT to 'true' in your environment.

       Either one will allow you to use the 32-bit binaries, but please be
       aware that these will disappear in a future Android SDK release.
       Consider moving to a 64-bit Linux system before that happens.

Setting SHELL variable to /bin/bash doesn't help.
Related problem:https://stackoverflow.com/questions/36482964/ubuntu-android-studio-error-running-emulator-cannot-decide-host-bitness-32-bit

**Comment by DavidPerezIngeniero** [comment]
Another problem:
```
# emulator -force-32bit @samsung_galaxy_s6_8.1
sh: 1: file: not found
sh: 1: file: not found
WARNING: Cannot decide host bitness because $SHELL is not properly defined; 32 bits assumed.
PANIC: Missing emulator engine program for 'x86' CPU.

```

**Comment by DavidPerezIngeniero** [comment]
```
# md5sum tools/emulator emulator/emulator
1f543126804da2bee38f104bec4418e5  tools/emulator
b700b0f469e61a09d0ee57d85dd19f19  emulator/emulator
```
Which one is valid?

**Comment by DavidPerezIngeniero** [comment]
[Possible workaround](https://github.com/ksoichiro/dockerfiles/issues/3)

**Comment by DavidPerezIngeniero** [comment]
The problem is maybe related to the fact that my Linux host is a virtual machine, by using `vmware`.

**Comment by DavidPerezIngeniero** [comment]
Solved by installing in my Linux host the CPU HAXM instructions emulation.

**Comment by gMan1990** [comment]
> Solved by installing in my Linux host the CPU HAXM instruction emulation.

how ?

**Comment by mh4nx7net** [comment]
> > Solved by installing in my Linux host the CPU HAXM instruction emulation.
> 
> how ?

here's for documentation
`https://developer.android.com/studio/run/emulator-acceleration`

**Comment by Kalela** [comment]
Do I install HAXM into the docker image? For me, It opens the emulator when I use the provided `  docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1 ` command. But I can't restart the emulator after rooting.
![image](https://user-images.githubusercontent.com/33759757/185997420-fa44b820-1ddc-4adc-a4f2-ec94606104bd.png)
