### ISSUE TITLE
Allow Control Over Appium Version via environment variable?

### ISSUE THREAD

**Issue by fbrandao** [budtmo/docker-android#209]
Currently to the best of my knowledge there is no mechanism to configure the appium server version if you use pre built images like for example budtmo/docker-android-x86-7.1.1.

In my case appium 1.15 introduced a new bug, and without using an older version some test scenarios simply are not executable.

Would it be possible to build de appium server components after startup of the container so we could pass an environment variable that would allow to setup the version?

The base docker image of appium has this functionality so i assume it should be portable across.

**Comment by budtmo** [comment]
Hi @fbrandao , 

no, I wont support it, because it make user to wait for the installation process (user want use any tool that is fast and ready to use). But the good news is that this tool is integrated with SaltStacks, so you can use SaltStack to control the container and do whatever you please.

**Comment by fbrandao** [comment]
Hi @budtmo 
Thanks for you response.

I understand completely, do you think its possible for me to build myself the docker-android-x86-7.1.1 image with a different appium version in order to use it ?
