### ISSUE TITLE
Emulator not starting when starting container

### ISSUE THREAD

**Issue by vlasr** [budtmo/docker-android#216]
## 💬 Questions and Help

Hi,

The emulator with specified device do not start automatically as shown in documentation. 

I used both cmd line or yml file to start container.

docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1

The emulator with device Samsung Galaxy S 6 is not launched. How can I start an emulator for a specific device?

Thank you!

**Comment by asimell** [comment]
Are you using a virtual machine? Do you have nested virtualization enabled?

At least VirtualBox doesn't support nested virtualization for Intel CPUs. I was facing the same issue with VB, but I created a Hyper-V Ubuntu virtual machine and the emulator started automatically.

**Comment by evg-yakovlev** [comment]
I faced this behavior on the Mac system. 
And in CircleCI, the emulator doesn't start either. 
In both cases docker container's status 'unhealthy'

**Comment by budtmo** [comment]
it doesnt support OSX, please read the readme
