### ISSUE TITLE
Building flutter application inside container

### ISSUE THREAD

**Issue by alessss** [budtmo/docker-android#221]
I'm trying to build android app with flutter inside https://github.com/budtmo/docker-android container.

I install flutter inside the container (flutter doctor says everything is ok), clone latest version of my code.

When I run

>  flutter build apk --debug

 I get

> Resolving dependencies...                                           4.2s
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Transformation hasn't been executed yet
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done                         2.9s
> Gradle task assembleDebug failed with exit code 1

What's wrong? Looks like the container is intended for building android apps?

**Comment by budtmo** [comment]
Hi @alessss , 

probably you miss other dependency(ies) that is(are) needed to build your application. Feel free to open the PR to add that dependency(ies) inside the Docker container.

**Comment by alessss** [comment]
Usind javiersantos/android-ci:28.0.3 to build application fixed the issue. Thanks.
