### ISSUE TITLE
Emaultor not launching in macOS Mojave

### ISSUE THREAD

**Issue by 4runl0g** [budtmo/docker-android#226]
## 🐛 Bug Report

Operating System: 
MacOSMojave

Docker Image:
budtmo/docker-android-x86-8.1

Docker Version:  
Docker version 19.03.5

Docker-compose version (Only if you use it):  
docker-compose version 1.25.2

Docker Command to start docker-android:  
Using only 2 images from this docker-compose file (https://github.com/budtmo/docker-android/blob/master/docker-compose.yml). Only 2 images(selenium_hub & samsung_galaxy_web_7.1.1, removed real_device link) 
Running using $ docker-compose up -d
  
## Expected Behavior
Emulator launches perfectly in ubuntu 18.04, expected same in MacOS

## Actual Behavior
**Emulator not launching in MacOS** 
Note: Tried with & without Docker Toolbox
WARNING: Cannot decide host bitness because $SHELL is not properly defined; 32 bits assumed.
ERROR: 32-bit Linux Android emulator binaries are DEPRECATED, to use them
       you will have to do at least one of the following:

       - Use the '-force-32bit' option when invoking 'emulator'.
       - Set ANDROID_EMULATOR_FORCE_32BIT to 'true' in your environment.

       Either one will allow you to use the 32-bit binaries, but please be
       aware that these will disappear in a future Android SDK release.
       Consider moving to a 64-bit Linux system before that happens.

**Comment by budtmo** [comment]
it doesnt support OSX, please read the readme
