### ISSUE TITLE
Outdated contents of sources1810.list causes docker build to fail

### ISSUE THREAD

**Issue by anoppe** [budtmo/docker-android#227]
## 🐛 Bug Report

Operating System: 
macOS 10.15.3

Docker Image:
budtmo/docker-android-x86-10.0

Docker Version:  
Docker Desktop v2.2.0.3

Docker-compose version (Only if you use it):  
N/A

Docker Command to start docker-android:  
N/A
  
## Expected Behavior
docker build completes without errors

## Actual Behavior
An image is build based on `budtmo/docker-android-x86-10.0` (i.e. `FROM budtmo/docker-android-x86-10.0`) because we need some additional robot framework libraries etc.
This morning I purged my docker images and rebuilt the image from scratch but the command halted with an error.

The docker build command ends with this error:
```E: The repository 'http://security.ubuntu.com/ubuntu cosmic-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic Release' does not have a Release file.
W: Conflicting distribution: https://repo.polyverse.io/deb/ubuntu/bionic/binary_amd64 main/ InRelease (expected main/ but got bionic)
W: Conflicting distribution: https://repo.polyverse.io/deb/ubuntu/bionic-updates/binary_amd64 main/ InRelease (expected main/ but got bionic)
W: Conflicting distribution: https://repo.polyverse.io/deb/ubuntu/bionic-security/binary_amd64 main/ InRelease (expected main/ but got bionic)
The command '/bin/sh -c apt update && apt install python3 -y  && apt install python3-pip -y && apt install git -y && apt install sudo -y && apt install nodejs -y  &&     pip3 install robotframework docutils requests robotframework-requests robotframework-appiumlibrary numpy opencv-python scipy matplotlib scikit-image scikit-learn ipython imutils &&     pip3 install -e git+https://github.com/FoodLogiQ/robotframework-imaplibrary.git#egg=robotframework-imaplibrary &&     sudo npm i -g appium --chromedriver-skip-install' returned a non-zero code: 100
```
I found out that the Dockerfile that is used to build the `budtmo/docker-android-x86-10.0` image, adds a custom apt source file to the `/etc/apt/sources.list.d/` directory: [sources1810.list](https://github.com/budtmo/docker-android/blob/master/docker/configs/sources1810.list). This file refers to Ubuntu Cosmic repositories, which are EOL.
I've added a `RUN` command to our Dockerfile that removes this sources1810.list, and as far as I see at this moment, our tests complete with success.
If you _really_ need this Ubuntu 18.10 repositories (_I would suggest to use an LTS version instead_), then a way to resolve this issue is to change the contents of that file to point to `http://old-releases.ubuntu.com/ubuntu/` instead.

**Comment by budtmo** [comment]
should be fixed in the new release
