### ISSUE TITLE
Unable to launch Docker Android UI from Web browser

### ISSUE THREAD

**Issue by mspshru** [budtmo/docker-android#228]
## 🐛 Bug Report

Operating System:
Ubuntu 18.04

Docker Image:
budtmo/docker-android-x86-8.1

Docker Version: 
18.09.2

Docker Command to start docker-android:  
docker run budtmo/docker-android-x86-8.1:latest
  
## Expected Behavior
I expect Docker Android UI to be seen when I launch Web browser and type `http://172.17.0.1:6080`. I found this IP from output of `ifconfig`'s `docker0`. 

## Actual Behavior
Web browser says 
```
Unable to connect

Firefox can’t establish a connection to the server at 172.17.0.1:6080.
```

**Comment by budtmo** [comment]
please use localhost
