### ISSUE TITLE
Add Password to VNC

### ISSUE THREAD

**Issue by Hackami** [budtmo/docker-android#232]
## 🚀 Feature Request

Idea: 
Need the ability to add VNC password in environment variables when creating docker

Problems that want to be solved:
The simulator is now passwordless accessible on the internet!

Note:  
It can increase the number of use-cases for using this docker.

**Comment by budtmo** [comment]
it should be fixed in version [1.8-p16](https://github.com/budtmo/docker-android/releases/tag/1.8-p16)
