### ISSUE TITLE
Proxy not working!

### ISSUE THREAD

**Issue by Triumvare** [budtmo/docker-android#235]
I have tried to set a proxy for an android container, but it's not working.

there is the way i have tried to set proxy
docker run --privileged -d -p 6080:6080 -p 5555:5555 -e DEVICE="Nexus 5" -e HTTP_PROXY="http://login:password@ip:port/" -e HTTPS_PROXY="http://login:password@ip:port/" -e ENABLE_PROXY_ON_EMULATOR=true -e NO_PROXY="localhost" --name device_1 budtmo/docker-android-x86-10.0

but when check an IP on android it's my PC's IP, not proxy

What I'm doing wrong?

**Comment by yintro4ha** [comment]
@Triumvare , it seems the existing proxy setting "HTTP_PROXY/HTTPS_PROXY" does not support `login:password`

Source code:
https://github.com/budtmo/docker-android/blob/2461a6e832d39252c2c080a4b528dbb36bc94851/src/utils.sh

@budtmo , can we support the proxy setting with auth? 


Example code: 
```bash
adb shell "content update --uri content://telephony/carriers --bind user:s:"$HTTP_RROXY_USER" --bind password:s:"$HTTP_RROXY_PASSWORD" --where "mcc=310" --where "mnc=260""
```
