### ISSUE TITLE
Sidebar crashes emulator

### ISSUE THREAD

**Issue by mauriciotoledo10** [budtmo/docker-android#238]
## 🐛 Bug Report

Operating System: 

Docker Image: budtmo/docker-android-x86-7.1.1, budtmo/docker-android-x86-8.1, budtmo/docker-android-x86-8.0, budtmo/docker-android-x86-10.0

Docker Command to start docker-android:  
docker run --privileged -d -p 6080:6080 -p 4723:4723 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S8" -e EMULATOR_ARGS="-no-snapshot-load -partition-size 512 -camera-back webcam0" --name android-container budtmo/docker-android-x86-8.1

Hi guys, i tested with a lot of devices and android versions, with Firefox NoVnc and Chrome NoVnc, same issue for everything... When i click anywhere on sidebar, emulator crashes. Anyone know how to fix or how to hide the sidebar? 

Thanks

**Comment by ssmuthukumaran** [comment]
Looks similar to [Issue 207](https://github.com/budtmo/docker-android/issues/207)

**Comment by 0jpq0** [comment]
docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 **-e QTWEBENGINE_DISABLE_SANDBOX=1** ...
ref: https://github.com/budtmo/docker-android/issues/223#issuecomment-599894986

**Comment by budtmo** [comment]
duplicated #223
