### ISSUE TITLE
Long time to start emulator 

### ISSUE THREAD

**Issue by samisamara19881** [budtmo/docker-android#244]
I'm simply trying to start emulator using the following image: budtmo/docker-android-x86-8.0 (Samsung Galaxy S9) using Kubernetes.
Its take around 4-5 mins to emulator to start (hang on Google icon), And after it's up it's take also long time to install application, It's normal time? If no, what can be the reason for that?
I ran it on 16Cores,32GB Ram machine

**Comment by kayner** [comment]
Same problem for any other image. 8 cores, 16gb RAM, but I don’t think it matters.
@budtmo are there any recommendations on this?

**Comment by vovinio** [comment]
One of the fastest combinations I've experienced is Nexus 5 with android 7.1.1

**Comment by vovinio** [comment]
sudo docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S10" -e EMULATOR_ARGS="-memory 8192 -partition-size 8096" --name android-container budtmo/docker-android-x86-11.0

You can try increase the memory and partition-size, it helped in my case and made the emulator to perform much better.
