### ISSUE TITLE
KVM Problem running the emulator

### ISSUE THREAD

**Issue by mateovalenciaeo** [budtmo/docker-android#247]
Hi, since yesterday I am trying to launch a simple demo Appium test for an Android App but I am having the following error in the Appium Server:
x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable 
When I try egrep -c '(svm|vmx)' /proc/cpuinfo, I got 0 what means that KVM is not usable for this docker container. I want to know if there is any solution for this because I think your docker image is wonderful and I really want to know if there is any solution. I am new at Appium and the Automation stuff but I want to learn and try with your docker image.
First I run your docker container in a Mac OS Catalina and also I tried in a Ubuntu 18.04 running in VMWare.

**Comment by kevinaj** [comment]
You must enable nested virtualization in VMWare in order to run KVM in a vm. This tutorial might help you out if you're using VMWare Fusion: [https://graspingtech.com/nested-virtualization-mac/](https://graspingtech.com/nested-virtualization-mac/)
