### ISSUE TITLE
your docker does not work for me

### ISSUE THREAD

**Issue by jankowskimarcin** [budtmo/docker-android#249]
Hello 

I'm trying with your environment but emulator seems doesn't work for me 

I have run command

docker run \
--privileged \
-d \
-p 6080:6080 \
-p 4734:4734 \
-p 5554:5554 \
-p 5555:5555 \
-v $PWD/samppaA10.apks:/root/tmp \
-e DEVICE="Samsung Galaxy S6" \
-e APPIUM=true \
-e APPIUM_HOST="127.0.0.1" \
-e APPIUM_PORT=4734 \
--name android-container \
budtmo/docker-android-x86-10.0

root@087b7b5d6505:~# emulator -force-32bit -avd samsung_galaxy_s6_10.0
sh: 1: file: not found
sh: 1: file: not found
WARNING: Cannot decide host bitness because $SHELL is not properly defined; 32 bits assumed.
PANIC: Missing emulator engine program for 'x86' CPU.

## 💬 Questions and Help

**Please make sure that it is an issue / a feature request. If it is a question / help wanted, please visit [our group chat](https://gitter.im/budtmo/docker-android). Thank you!**

**Comment by kevinaj** [comment]
Having the same problem with regards to the host bitness. Prefixing `SHELL=/bin/bash` prior to the emulator command doesn't help. Also tried setting the SHELL environment variable via Docker at container launch with no luck.

**Comment by Szaki** [comment]
I had the same issue, then I saw https://github.com/budtmo/docker-android/issues/216, https://github.com/budtmo/docker-android/issues/218 and https://github.com/budtmo/docker-android/issues/247, so I checked KVM on my computer.
Virtualisation was disabled in BIOS so I enabled it, installed KVM, rebooted, ran the container and the emulator was up and running all of the sudden.
More info about virtualisation and KVM: https://help.ubuntu.com/community/KVM/Installation

**Comment by TimurNurlygayanov** [comment]
Szaki, Thank you! You saved me a day of debugging this issue - I was tried to run it inside VM in Google cloud and also found that the android emulator is dead inside the docker container

**Comment by TheLightTheMan** [comment]
Ok. So a Docker is a self contained space on my CPU that may hold programs for me?

Thank you.
Lord Shaun William Patrick Tepel

________________________________
