### ISSUE TITLE
2 small questions (adb connect + emulators+jenkins)

### ISSUE THREAD

**Issue by Gardosen** [budtmo/docker-android#256]
## 💬 Questions and Help

Hello, 

first of all i wanna let you know that i am amazed of how well this works. 
I have created a simple docker-compose file based on your explanation and it created 30 emulators on my machine with the help of the scale system. (still sad that docker-compose does not support scale + container_name, but whatever)

now i have two small problems and i hope you can help me.

1. in order to connect the emulators to my host adb i am using the following shell script

```
#!/bin/bash

for i in $(docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq) |grep 'android-compose_nexus' |grep -Eo '172.*')
do
	echo  "connecting $i to adb"
	adb connect $i:5555
done
```

but i was wondering if there is a chance to give the container the adb instance of the host, so the container can connect itself to the adb host? i tried some approaches on a combination with volume (give the adb to the container) and commands (execute an adb connect to the host) but was not successfull.

2. I wanna use those emulators in jenkins, but also jenkins is dockerized for me, so the adb of my host machine which i am connecting the emulators to with my script, is not the one jenkins knows. 
how can i give jenkins this adb as it's source of truth, so jenkins can find the connected devices? i am using the connector plugin on jenkins, so jenkins is waiting for those devices via adb :/ 

I hope you can help me.

Thanks in advance, and keep up the great work!

**Comment by Gardosen** [comment]
Issue solved, i create two scripts.

one which filters all emulator ips running on the docker host, and which writes it to a file
then linking a volume to the jenkins docker which contains this file
and inside the jenkins i run a second script which reads out these ips and links the adb of jenkins to the docker emulators :) 

works fine
<img width="1298" alt="Bildschirmfoto 2020-08-31 um 10 55 22" src="https://user-images.githubusercontent.com/415867/91708335-771e3b80-eb81-11ea-96f7-77bed70fce54.png">

**Comment by pierrepicaud** [comment]
I'm having a similar issue, I have an on demand jenkins runner, and the host's adb connect successfully to the ip:5555 of the container but no devices shown, any idea? Thanks in advance
