### ISSUE TITLE
Appium crash on startup [AKS Example Not working]

### ISSUE THREAD

**Issue by a7i** [budtmo/docker-android#265]
## 🐛 Bug Report

I am using the example provided on AKS but running into issues with real-device deployment

Operating System: 

Ubuntu 18.04 (running on Azure Kubernetes Service)

Docker Image:

`appium/appium`
`budtmo/docker-android-x86-7.1.1`

Docker Version:  

Kubernets 117

Docker-compose version (Only if you use it):  

Docker Command to start docker-android:  

  
## Expected Behavior

real-device pod is not coming up due to the following stack-trace:
```
* daemon not running; starting now at tcp:5037
* daemon started successfully
Devices found: 0
[Appium] Welcome to Appium v1.18.1
[Appium] Non-default server args:
[Appium]   logFile: /var/log/appium.log
[Appium]   nodeconfig: /root/nodeconfig.json
[Appium] Syntax error in node configuration file: Unexpected token c in JSON at position 364
Fatal Error: Syntax error in node configuration file: Unexpected token c in JSON at position 364
    at Object.errorAndThrow (/usr/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
    at postRequest (/usr/lib/node_modules/appium/lib/grid-register.js:48:12)
    at registerNode (/usr/lib/node_modules/appium/lib/grid-register.js:26:3)
    at main (/usr/lib/node_modules/appium/lib/main.js:152:7)
```

## Actual Behavior

real-device pod comes up successfully.

**Comment by a7i** [comment]
@stazdx any insights?

**Comment by a7i** [comment]
Turns out that it requires the file `/root/nodeconfig.json` to be present

**Comment by stazdx** [comment]
> Turns out that it requires the file `/root/nodeconfig.json` to be present

Sorry for the delay and thanks for sharing the solution @a7i  !
