### ISSUE TITLE
Migrate data to another machine

### ISSUE THREAD

**Issue by mauriciotoledo10** [budtmo/docker-android#269]
Hi guys, i want to migrate all data of my Android image to another machine using this project, like all my apps and data inside the Android. Is that possible?

Thanks anyway!

**Comment by mauriciotoledo10** [comment]
?

**Comment by btlucas** [comment]
I'm having the same difficulty but a workaround I found was to create a image commiting my container changes. Following this: https://stackoverflow.com/questions/44480740/how-to-save-a-docker-container-state 
Don't know why but the resulting image ends up being way havier than the original, even though I've only installed one app.

**Comment by budtmo** [comment]
Hi, 

please use docker volume to backup your data. I will close the issue as it is not a bug
