### ISSUE TITLE
emulator not start

### ISSUE THREAD

**Issue by mynamecool** [budtmo/docker-android#271]
## 💬 Questions and Help

**Please make sure that it is an issue / a feature request. If it is a question / help wanted, please visit [our group chat](https://gitter.im/budtmo/docker-android). Thank you!**
Why do I follow the tutorial docker，but emulator not to start

**Comment by mynamecool** [comment]
every images

**Comment by TheLightTheMan** [comment]
My apologies. Busy. I'll set it up in the morning. Thank you

**Comment by TheLightTheMan** [comment]
So much to do

**Comment by budtmo** [comment]
Hi @mynamecool , 

please try to reach our group chat for question. I will close this ticket then.
