### ISSUE TITLE
Docker container with appium runs on all my laptops but doesn't run on the cloud

### ISSUE THREAD

**Issue by rieszrt** [budtmo/docker-android#272]
## 🐛 Bug Report

Operating System: 

Docker Image:

Docker Version:  

Docker-compose version (Only if you use it):  

Docker Command to start docker-android:

**Comment by TheLightTheMan** [comment]
Hi. Will you please help me set this up on my devices please. I am running an HP business laptop. A Samsung S 20 Ultra and a Samsung smart hub

Thank you.
Lord Shaun William Patrick Tepel

________________________________

**Comment by TheLightTheMan** [comment]
I have a lot to do before Christmas. The web says I need Docker to house something to run Microsoft Tunnel. The VPN I am setting up. Please 😇😇😇.

Thank you.
Lord Shaun William Patrick Tepel

________________________________

**Comment by TheLightTheMan** [comment]
Feel free to call the business Mobility number at 7807777049 or the office landline at 7809808307. Love & Respect. God bless 😇😇😇

Thank you.
Lord Shaun William Patrick Tepel

________________________________

**Comment by rieszrt** [comment]
sure, do you have skype?

**Comment by TheLightTheMan** [comment]
Yes sir...or Yes ma'am lol.

**Comment by TheLightTheMan** [comment]
thelighttheman@thelightthemen.com

Thank you.
Lord Shaun William Patrick Tepel

________________________________

**Comment by TheLightTheMan** [comment]
That is the business email

Thank you.
Lord Shaun William Patrick Tepel

________________________________
