### ISSUE TITLE
Bug while Using Docker-android using novnc through ngrok, 

### ISSUE THREAD

**Issue by developeranaz** [budtmo/docker-android#273]
#Bug while Using Docker-android using novnc through ngrok
![Screenshot 2020-12-26 182726](https://user-images.githubusercontent.com/71500526/103152053-14912100-47aa-11eb-94c3-465375af3c09.png)

**Comment by budtmo** [comment]
Hi @developeranaz , 

There is nothing to do with ngrok. Probably you need to enable kvm, it is written in documentation as well. I will close the ticket and feel free to reopen it if needed.
