### ISSUE TITLE
maxSession=6 may break appium test execution

### ISSUE THREAD

**Issue by xuanzhaopeng** [budtmo/docker-android#275]
## 🐛 Bug Report

For code : https://github.com/budtmo/docker-android/blob/master/src/app.py#L194

```
'configuration': {
            'cleanUpCycle': 2000,
            'timeout': selenium_timeout,
            'proxy': selenium_proxy_class,
            'url': 'http://{host}:{port}/wd/hub'.format(host=appium_host, port=appium_port),
            'host': appium_host,
            'port': appium_port,
            'maxSession': 6,
            'register': True,
            'registerCycle': 5000,
            'hubHost': selenium_host,
            'hubPort': selenium_port,
            'unregisterIfStillDownAfter': 120000
        }
```

It seems means that for one Android Emulator, it can run 6 tests in parallel? but I believe it's impossible,  we only have 1 emulator, in the same moment, we should only run 1 session.

Could you pls correct me if I'm wrong? @budtmo , if you agree, I could make a PR to make `maxSession` to 1

**Comment by budtmo** [comment]
Hi @xuanzhaopeng , 

yes, you are right. Please feel free to create a PR for it.
