### ISSUE TITLE
Error: x86 emulation currently requires hardware acceleration

### ISSUE THREAD

**Issue by gromanas** [budtmo/docker-android#278]
## 🐛 Bug Report

Operating System: 
macOS Catalina 10.15.7

Android Studio:
Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin

HAXM installer:
7.5.1

Docker Image:
`budtmo/docker-android-x86-11.0` and also tested on `budtmo/docker-android-x86-10.0` and `budtmo/docker-android-x86-8.1`

Docker Version:  
Engine 20.10.2

Docker Command to start docker-android:  
```sudo docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 4723:4723 -p 5555:5555 -e APPIUM=true -e DEVICE="Samsung Galaxy S9" --name android-container budtmo/docker-android-x86-10.0```
  
## Expected Behavior
It's the first time I used it. I am really thrilled with the idea of having emulators inside docker. I supposed that I should see the emulator started inside the container using the  NoVNC `http://localhost:6080/`.

## Actual Behavior
Only Appium is started. When I try to start manually the Emulator through `Terminal Emulator` I get `Error: x86 emulation currently requires hardware acceleration`.
```The error Error: handleCpuAcceleration: feature check for hvf occured and the emulator couldn't start```

## Notes:
I have used also haxm/CheckTool from:
https://github.com/intel/haxm/tree/master/CheckTool 
and it seems that everything is working as expected

```./checktool --verbose
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       *  Yes
VMX enabled         *  Yes
EPT supported       *  Yes
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    *  Not Applicable
OS version          *  macOS 10.15.7
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)
```  

## Screenshot
<img width="1426" alt="Screenshot 2021-01-21 at 10 07 45" src="https://user-images.githubusercontent.com/48865319/105325395-3927bf80-5bd5-11eb-9e3a-c35ab5541d71.png">

**Comment by TheLightTheMan** [comment]
What is this?

**Comment by gromanas** [comment]
Hello @TheLightTheMan! Could you please be more specific? 

> What is this?

**Comment by budtmo** [comment]
Hi @gromanas , 

the image cannot be used on Mac or Windows machine, sorry. I will close the ticket as this concern is already known and written in readme.
