### ISSUE TITLE
Android Emulator does not start

### ISSUE THREAD

**Issue by omid96** [budtmo/docker-android#280]
## 🐛 Bug Report

Operating System: 
Ubuntu 18.04.5 LTS, Ubuntu 20.04.1 LTS

Docker Image:
budtmo/docker-android-x86-8.1, etc

Docker Version:  
20.10.1, build 831ebea

Docker Command to start docker-android:  
d docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1
  
## Expected Behavior
After running docker run command explained above docker container should come up and Android Emulator gets ready for use

## Actual Behavior
Sometimes Android Emulator does not come up and there is nothing to see and after a short time container status become unhealthy

**Comment by tonigonzalez** [comment]
I had the same bug today and it was something quite dumb. I didnt have enabled the virtualization extensions on the bios. If you are running a linux host, check if /dev/kvm exists or not (it should)
