### ISSUE TITLE
Adb not working

### ISSUE THREAD

**Issue by btlucas** [budtmo/docker-android#284]
## 🐛 Bug Report

Operating System: 
Ubuntu 20.04

Docker Image:
Tried multiple images, none of them worked: budtmo/docker-android-real-device, budtmo/docker-android-x86-11.0 and budtmo/docker-android-x86-7.1.1

Docker Version:  
20.10.5

Docker-compose version (Only if you use it):  
1.27.3

Docker Command to start docker-android:  
docker-compose up -d 
or
docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 --name android-container-appium budtmo/docker-android-real-device
  
## Expected Behavior
Android running on docker and able to use adb to connect to it

## Actual Behavior
![image](https://user-images.githubusercontent.com/24281143/113609031-a8804d80-9621-11eb-9ba4-b8480dee352a.png)

**Comment by typoworx-de** [comment]
How can this be solved? Same here trying to connect directly using container-IP using ADB is being refused.

**Comment by lenlaw** [comment]
Same error here. (host has a connected device). Any hints at all welcome.
