### ISSUE TITLE
All apps removed after docker container restart

### ISSUE THREAD

**Issue by ChandraNakka** [budtmo/docker-android#286]
Dear @budtmo and dev team,

I have installed some apps on docker-android's AVD. After `docker stop` and `docker start` commands. AVD becomes fresh and all installed apps cleared.

How to get my apps and work saved on AVD even after `docker stop` & `docker start` commands.

**I have already tried these arguments**

> -v local_backup/.android:/root/.android
> -v local_backup/android_emulator:/root/android_emulator

But, no use...

Please solve this issue. Thanks :)

**Comment by scottwallacesh** [comment]
I believe this is caused by an incorrect check for existing containers:
https://github.com/budtmo/docker-android/blob/49113f2cb4425c5d0724880aefe528f5762b148f/src/app.py#L59

It should be, 
```python
 if any('hw.device.name = {}'.format(device_name) in line for line in f): 
```

**Comment by markkong318** [comment]
Hi I had the same situation before and found that the two formats in scottwallacesh are possible in my test
It is better to include the two cases I think
