### ISSUE TITLE
Installed app get remove after restarting emulator

### ISSUE THREAD

**Issue by omid96** [budtmo/docker-android#291]
## 🐛 Bug Report

Operating System: 
Arch Linux

Docker Image:
budtmo/docker-android-x86-11.0

Docker Version:  
20.10.7

Docker-compose version (Only if you use it):  

Docker Command to start docker-android:  
 docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-11.0
  
## Expected Behavior
Like other images I want to preserve user data like installing apps will not removed after restarting.

## Actual Behavior
After I install application with adb on just android 11 emulator, all installed application will get remove after restarting emulator or the docker itself. This is only for Android 11 image. Also I have checked on my own avdmanager to run Android 11 and it was all ok.

**Comment by ireneu** [comment]
Also stumbled upon this issue. I've opened PR #294 to resolve it, but it still needs a little work 🙃

**Comment by budtmo** [comment]
PR is merged and new version is released
