### ISSUE TITLE
Disable noVNC/chromedriver flag?

### ISSUE THREAD

**Issue by vinhjaxt** [budtmo/docker-android#292]
## No noVNC
Thank you for a great repo.
In my case I don't want any VNC programs (including noVNC), I just want to pure Android with terminal/shell to run dalvikvm.
Is there any flag to disable/uninstall noVNC/chromedriver etc.

Thank you.

**Comment by budtmo** [comment]
disabled noVNC and other configurations are supported on the current version. I will close the issue but feel free to reopen it.
