### ISSUE TITLE
Bug in is_initialized - always returns False

### ISSUE THREAD

**Issue by yoyole123** [budtmo/docker-android#296]
https://github.com/budtmo/docker-android/blob/caf2cb2cd80b69442e054662790ac8f97477f57b/src/app.py#L59

Took me some time to realize why I can't seem to persist my device's state using this emulator.
I found out that there is a bug in this script which forces the emulator to create the emulated device's filesystem from scratch every time.

The real config.ini file has white spaces around the equal sign ("hw.device.name = <DEVICE_NAME>"), so it never finds the reference and always assumes a new device is being used.

I recommend changing the condition in line 59 to:
```
import re

regex_string = 'hw.device.name( |\t)*=( |\t)*{}'.format(device_name)
with open(config_path, 'r') as f:
    if any(re.match(regex_str, line) for line in f):
        return True
```

**Comment by budtmo** [comment]
it should be fixed on version [v1.9-p8](https://github.com/budtmo/docker-android/releases/tag/v1.9-p8). Feel free to reopen the ticket
