### ISSUE TITLE
Nothing display

### ISSUE THREAD

**Issue by Geruays** [budtmo/docker-android#301]
## 🐛 Bug Report

Operating System: 
Ubuntu Last

Docker Image:

Docker Version:  
last

ihave run but its just like this

![Capture](https://user-images.githubusercontent.com/84316160/131295798-9a17d261-cf45-4d3d-b5cd-96ab1bb4142f.PNG)

**Comment by Geruays** [comment]
Right no one else matters to me

**Comment by tywldx** [comment]
me 2
