### ISSUE TITLE
devices always offline

### ISSUE THREAD

**Issue by hhhaiai** [budtmo/docker-android#307]
### Operating System: 
Ubuntu 20.04

### platform
github action. newest docker. 

### LOG
```
=================================安装模拟器完毕，查看所有容器===================================
CONTAINER ID   IMAGE                            COMMAND                  CREATED        STATUS                                     PORTS                                                                                                                          NAMES
74f87f72b60f   budtmo/docker-android-x86-12.0   "/bin/sh -c '/usr/bi…"   1 second ago   Up Less than a second (health: starting)   4567/tcp, 0.0.0.0:5554-5555->5554-5555/tcp, :::5554-5555->5554-5555/tcp, 4723/tcp, 0.0.0.0:6080->6080/tcp, :::6080->6080/tcp   ac12
=================================安装模拟器完毕，查看运行的容器===================================
CONTAINER ID   IMAGE                            COMMAND                  CREATED        STATUS                                     PORTS                                                                                                                          NAMES
74f87f72b60f   budtmo/docker-android-x86-12.0   "/bin/sh -c '/usr/bi…"   1 second ago   Up Less than a second (health: starting)   4567/tcp, 0.0.0.0:5554-5555->5554-5555/tcp, :::5554-5555->5554-5555/tcp, 4723/tcp, 0.0.0.0:6080->6080/tcp, :::6080->6080/tcp   ac12
ac12
=================================安装模拟器完毕，adb查看设备===================================
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
emulator-5554	offline
```

**Comment by amiralam0** [comment]
i have this too

**Comment by shivergard** [comment]
me too :/

**Comment by xMH85x** [comment]
I had the same issue when I was using docker-desktop context. After switching to default, it works now.
You can check that with the following command: 

docker context ls

if default is not in use, type: 

docker context use default

It worked for me

**Comment by sierraleonez** [comment]
Actually I run the container inside a compute engine that doesn't support [nested virtualization,](https://cloud.google.com/compute/docs/instances/nested-virtualization/enabling) , and after I create new instance with nested virtualization, It works!
But I also tried DinD (Docker in Docker) approach, and faced this issue as well (even with the nested virtualization enabled), seems like it require lv 2 nested virtualization to achieve the result I expected.

**Comment by hhhaiai** [comment]
I have a plan :  step 1: If need ,  install SDK env and emulator tools ; step 2. config cutsom devices and run ;  step 3: wait  success and some config.  

one lib has some commond:(https://github.com/ReactiveCircus/android-emulator-runner)
Chinese doc:  https://www.yuque.com/sanbo/npozvp/ming-ling-xing-xin-jian-mo-ni-qi-androidemulatorru

**Comment by budtmo** [comment]
please check the virtualization configuration. I will close the issue for now, but feel free to reopen it
