### ISSUE TITLE
How can I find the docker volume that is being used?

### ISSUE THREAD

**Issue by cocoonkid** [budtmo/docker-android#318]
I checked all in /var/lib/docker/volumes

 docker ps -q | xargs docker container inspect -f '{{ .Name }} {{ .HostConfig.Binds }}'
```
/android-container []

```

But there must be the data somewhere?

In addition how can I specify my own custom volume?

Just add ``` -v ~/data:/data ``` to docker run ?

**Comment by scottwallacesh** [comment]
I have a persistent Android installation (i.e. long-lived) and I bind mount:
* `/root/.android/`
* `/root/android_emulator`

**Comment by sandyboxy** [comment]
> I have a persistent Android installation (i.e. long-lived) and I bind mount:
> 
>     * `/root/.android/`
> 
>     * `/root/android_emulator`

Hi @scottwallacesh,
I tried to set volumes in my docker-file in this way but device resets (with data loss) every time I restart the docker:
```
    volumes:
      - ./android:/root/.android/
      - ./android-emulator:/root/android_emulator
```
