### ISSUE TITLE
What's Polyverse?

### ISSUE THREAD

**Issue by zek** [budtmo/docker-android#322]
What is the purpose of following commit?

https://github.com/budtmo/docker-android/commit/4ac0bebe99a6267d0e1df0f4f74977471352bfbd

**Comment by budtmo** [comment]
everything is written in readme

**Comment by zek** [comment]
I have a fresh ubuntu 20.04 installation. All incoming ports are closed on the hardware level.
There is a single running docker container in this fresh server and somehow it's getting hacked.
So I'm trying to find out how the attacker acceses my machine.

**Comment by budtmo** [comment]
Hi @zek , 

have you tried to track down where the attack / traffic came from? could you also give me the list of running processes of that running docker-container and your host machine? I will try to help
