### ISSUE TITLE
Run Android docker image in docker running on a windows instead using a virtual machine and installing Ubuntu

### ISSUE THREAD

**Issue by MrSharpp** [budtmo/docker-android#324]
## 💬 Questions and Help

**Please make sure that it is an issue / a feature request. If it is a question / help wanted, please visit [our group chat](https://gitter.im/budtmo/docker-android). Thank you!**

Hey is it possible to run the android docker image in a docker running in windows instead of installing a VM ware and then installing Ubuntu then running this image?

and if its not possible right now, can i know why and  what happens behind the scenes so this is not possible with windows?

**Comment by KennyFrans** [comment]
You can, using wsl 2 like i did, just make sure wsl 2 installed and when installing docker for windows you select wsl2 over hyper-v for the engine

**Comment by budtmo** [comment]
Hi @KennyFrans , 

could you contribute to the documentation and document your setup and create a PR? others can benefit from it.

**Comment by SourCandy80** [comment]
That would be very nice if you could do that @KennyFrans 

I was just trying to set this up on windows and I am getting annoyed I cant have my program I'm making run on Windows AND Linux

**Comment by MrSharpp** [comment]
I think windows doesnt support nested virtualization so we cannot another emulator in a container or wsl.

**Comment by foureight84** [comment]
it works fine under wsl2. use this answer to enable nestedvirtualization

https://serverfault.com/a/1115773

**Comment by budtmo** [comment]
could you help with the documentation @foureight84 and create a PR? I will merge the PR because it might be useful for others.

**Comment by foureight84** [comment]
> could you help with the documentation @foureight84 and create a PR? I will merge the PR because it might be useful for others.

Will do in a few hours. :). I'm also trying to get it working behind traefik as well. I'll update documentation with PR after that is working too.

**Comment by budtmo** [comment]
documentation added on PR #379 . credits @foureight84
