### ISSUE TITLE
Android 13 support

### ISSUE THREAD

**Issue by 123dev** [budtmo/docker-android#331]
## 🚀 Feature Request

Hi, Android 13 is released, any plans on supporting it?
Thanks

**Comment by binithb** [comment]
Hi, is there anything preventing us from having an Android 13 image? This is becoming pretty important for continued usage of this project

**Comment by binithb** [comment]
@JoelWhitney  I see you made the PR for Android 12. Just wanted to check, are you aware of any blockers to support Android 13?
