### ISSUE TITLE
android project build failed 

### ISSUE THREAD

**Issue by AlbertShen0211** [budtmo/docker-android#347]
## 🐛 Bug Report

Operating System: 
MacBook Pro 11.6 (20G165)

Docker Image:
budtmo/docker-android-genymotion

Docker Version:  
4.8.1 (78998)

Docker-compose version (Only if you use it):  
1.29.2

Docker Command to start docker-android:  

  
## Expected Behavior
Build successful
Support jdk 11

## Actual Behavior

Build file '/tmp/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
      Your current JDK is located in /usr/lib/jvm/java-8-openjdk-amd64/jre
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 23s

**Comment by budtmo** [comment]
I will close the ticket as the latest docker image contains java-11. feel free to reopen it if needed.

**Comment by remi0s** [comment]
> I will close the ticket as the latest docker image contains java-11. feel free to reopen it if needed.

Was emulator wich contains playstore also added?
