### ISSUE TITLE
[🚀 Feature Request ]: Maybe you should give us some permissions. Need your image and my application to be containerized. But it does not let me do anything, neither to install something via docker-compose.yaml.

### ISSUE THREAD

**Issue by sterlan** [budtmo/docker-android#361]
### Idea

Maybe you should give us some permissions. Need your image and my application to be containerized. But it does not let me do anything, neither to install something via docker-compose.yaml.

### Probelm to solve

Maybe you should give us some permissions. Need your image and my application to be containerized. But it does not let me do anything, neither to install something via docker-compose.yaml.

**Comment by budtmo** [comment]
you can use the pro version or you can modify this project and build it by yourself. I will close the issue as the state is expected
