### ISSUE TITLE
[🚀 Feature Request ]: where is documention

### ISSUE THREAD

**Issue by ericzhao007** [budtmo/docker-android#367]
### Idea

not documention

### Probelm to solve

I use docker for window, and I am using WSL2, running but the emulator is not displayed in VNC, I mainly use the current version to the issue, is there a tutorial for using the current version

**Comment by budtmo** [comment]
HI @ericzhao007 , 

the project doesnt support windows OS. you need to use Linux VM to be able to run this project. I will close the issue as there is no plan to support any other OS at the moment.
