### ISSUE TITLE
unknown server OS 

### ISSUE THREAD

**Issue by annpeter** [budtmo/docker-android#393]
### Operating System

Ubuntu 18.04

### Docker Image

budtmo/docker-android:emulator_11.0

### Expected behaviour

the container start successfully

### Actual behaviour

docker run -d -p 6080:6080 -p 5555:5555 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container "budtmo/docker-android:emulator_11.0"

get error "unknown server OS "

<img width="1379" alt="image" src="https://github.com/budtmo/docker-android/assets/7344217/0d0ca653-94a4-4e1e-a3b0-48e2e5efcfa8">

**Comment by BlueClouDragon** [comment]
same issue

**Comment by energydrinksjunkie** [comment]
same issue

**Comment by BlueClouDragon** [comment]
it is because container name have quotemark

**Comment by annpeter** [comment]
@BlueClouDragon 
i removed the quotemark, it still the same.
and if i remove --device /dev/kvm it can start the container, but the system has been stuck on the startup screen.

<img width="1516" alt="image" src="https://github.com/budtmo/docker-android/assets/7344217/cc9fd371-4094-42db-8c00-2abb05fae9c4">

**Comment by BlueClouDragon** [comment]
try delete _11.0  and rewrite _11.0

**Comment by energydrinksjunkie** [comment]
had to run in with sudo, now it works

**Comment by annpeter** [comment]
run with sudo, it works.  @energydrinksjunkie  thanks.
