### ISSUE TITLE
[🐛 Bug ]: 

### ISSUE THREAD

**Issue by BlueClouDragon** [budtmo/docker-android#394]
### Operating System

Ubuntu

### Docker Image

budtmo/docker-android:emulator_11.0

### Expected behaviour

I mapped new port 7000 for javalin http server with "-p 7000:7000"

### Actual behaviour

but the docker 7000 port not accessible on host machine.
6080, 5554, 5555 can accessible on host machine but other ports are not accessible now.
Please help me how to make accessible other ports like 6080

**Comment by budtmo** [comment]
Hi @BlueClouDragon , 

I will close the issue as it is not the issue on this project because if I understood correctly that you try to map the port of your own service. maybe you can try to run your service on different container and put both containers in the same network. good luck btw.
