### ISSUE TITLE
[🚀 Feature Request ]: Emulator version 14.0

### ISSUE THREAD

**Issue by ath0mas** [budtmo/docker-android#396]
### Idea

Build and publish version 14.0 of the image.

### Probelm to solve

Follow possibility to create emulator for version 14.0 with Android SDK.

**Comment by budtmo** [comment]
Hi @ath0mas, 

Android 14 is added in [v2.3.0-p1 ](https://github.com/budtmo/docker-android/releases/tag/v2.3.0-p1).
