### ISSUE TITLE
[🐛 Bug ]: 

### ISSUE THREAD

**Issue by 806373995** [budtmo/docker-android#425]
### Operating System

windwos11

### Docker Image

docker-android:emulator_11.0

### Expected behaviour

create volume error

### Actual behaviour

create volume error ：
docker run -v F:/docker/dockerForAndroid/data/:/home/androidusr budtmo/docker-android:emulator_11.0
error message：
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/home/androidusr/docker-android/mixins/scripts/run.sh": stat /home/androidusr/docker-android/mixins/scripts/run.sh: no such file or directory: unknown.

**Comment by dogederp** [comment]
wait a second. What did you do to fix this?

**Comment by 806373995** [comment]
> wait a second. What did you do to fix this?

docker run -v data:/home/androidusr budtmo/docker-android:emulator_11.0

use this
